spring:
  application:
    name: ivory-be
  cloud:
    aws:
      s3:
        bucket: ivory
      credentials:
        access-key: ivory
        secret-key: ivory
      region:
        static: ap-northeast-2

  datasource:
    url: jdbc:mysql://localhost:3306/ivory?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

runner:
  url: http://

ivory-fe:
  url: http://